#!/bin/bash
read -p "Verification du commit (y/[n]) ?" yn < /dev/tty
yn=${yn:-n}
case $yn in
  [Yy]* )
    echo "commit verifie le $(date)" > suivi/commitInfo.txt
    git add suivi/commitInfo.txt
    exit 0;;
  [Nn]* )
    exit 0;;
esac
exit 0
